// json files
const formItemLayout = {
  labelCol: {
    xs: {
      span: 24,
    },
    sm: {
      span: 8,
    },
  },
  wrapperCol: {
    xs: {
      span: 24,
    },
    sm: {
      span: 18,
    },
  },
};
const country = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "North Korea",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "U.S. Virgin Islands",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const year = [
  1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
  1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985,
  1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
  1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
  2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024,
];
const price = [
  "50,000 to 100,000",
  "100,000 to 150,000",
  "150,000 to 200,000",
  "200,000 to 250,000",
  "250,000 to 300,000",
  "300,000 to 350,000",
  "350,000 to 400,000",
  "400,000 to 450,000",
  "450,000 to 500,000",
  "500,000 to 600,000",
  "600,000 to 700,000",
  "700,000 to 800,000",
  "800,000 to 900,000",
  "900,000 to 10,00,000",
  "10,00,000 to 11,00,000",
  "11,00,000 to 12,00,000",
  "12,00,000 to 13,00,000",
  "13,00,000 to 14,00,000",
  "14,00,000 to 15,00,000",
  "15,00,000 to 20,00,000",
  "20,00,000 to 25,00,000",
  "25,00,000 to 30,00,000",
  "30,00,000 to 35,00,000",
  "35,00,000 to 40,00,000",
  "40,00,000 to 45,00,000",
  "45,00,000 to 50,00,000",
  "50,00,000 to 75,00,000",
  "75,00,000 to 100,00,000",
  "100,00,000 to 200,00,000",
  "200,00,000 to 300,00,000",
  "300,00,000 to 400,00,000",
  "400,00,000 to 500,00,000",
];
const options = [
  {
    name: "property",
    subOptions: [
      "House",
      "Apartment",
      "Upper Portion",
      "Lower Portion",
      "Farm House",
      "Room",
      "Pent House",
    ],
  },
  {
    name: "plot",
    subOptions: [
      "Residential Plot",
      "Commercial Plot",
      "Agricultural Land",
      "Industrial Land",
      "Plot File",
    ],
  },
  {
    name: "commercial",
    subOptions: ["Office", "Shop", "Warehouse", "Factory", "Building", "Other"],
  },
];
const location = [
  {
    name: "Karachi",
    sublocation: [
      "Karachi Airport",
      "Baldia Town",
      "Board of Secondary Education",
      "Karachi Cantt",
      "City GPO",
      "Clifton",
      "COD",
      "Darul-uloom",
      "Defence Society",
      "Export Processing Zone",
      "Federal B Area",
      "Gulshan-e-Iqbal",
      "Habib Bank",
      "Hotel Metropole",
      "Jinnah Post Graduate Medical Center",
      "Karachi GPO",
      "Karachi University",
      "Keemari",
      "Korangi Creek",
      "Korangi GPO",
      "Landhi Colony",
      "Liaqatabad",
      "Liyari",
      "Malir Cantt",
      "Malir City",
      "Manghopir",
      "Manora",
      "MariPur-CE",
      "Maripur-FA",
      "Mehmoodabad",
      "Model Colony",
      "Murad Memon Goth",
      "National Cement Industry- DALMIA",
      "Nazimabad GPO",
      "New Karachi",
      "New Town GPO",
      "North Nazimabad GPO",
      "Orange Town",
      "PCSIR",
      "PECHS",
      "Pakistan Machine Tool Factory",
      "Pakistan Naval Armament Depot",
      "Pakistan Steel Mills",
      "Pakistan Steel Mills Town Ship",
      "Port Muhammad Bin Qasim",
      "Quaidabad",
      "Rafa-e-Aam Society",
      "SITE",
      "Saddar GPO",
      "Shah Faisal Colony",
      "Shahra-e-Faisal",
      "Sher Shah Colony",
      "Sindh Governor House",
      "Nishter Road",
    ],
  },
  {
    name: "Lahore",
    sublocation: [
      "Sukh Chain Society",
      "PASCO Housing Society",
      "Fransisi Town",
      "Sarshar Town",
      "Allama Iqbal Town",
      "Samanabad",
      "Gulshan E Ravi",
      "Sanda Khurd",
      "Sanat Nagar",
      "Karim Park",
      "Shad Bagh",
      "Faruque Ganj",
      "Baghban Pura",
      "Shalimar Town",
      "Herbuns Pura",
      "Ram Garh",
      "Ittehad Colony",
      "Ali Park",
      "Officers Colony",
      "Burj Colony",
      "Suparco Colony",
      "PCSIR Housing Scheme",
      "Punjab University",
      "Punjab University Hostel",
      "Shadman Colony",
      "Johar Town",
      "Airline Society",
      "Faisal Town",
      "Wafaqi Colony",
      "Bostan Colony",
      "Hamdard Chowk",
      "Bagrian",
      "Lake City",
      "Shabir Town",
      "Opf Housing Scheme",
      "NFC Town",
      "Nespak Society",
      "Aitchison Society",
      "Railway Housing Society",
      "Gawal Mandi",
      "Qila Gujarsing",
      "Mazang",
      "Gor",
      "Gulberg 3",
      "Gulbahar Colony",
      "Ghazi Road",
      "Nishtar Colony",
      "Bedian Road",
      "Cavalry Ground",
      "Punjab Society Near Dha",
      "DHA 1",
      "DHA 4",
      "DHA 7",
      "Chachowali",
      "Cantt",
      "Askrai Villa 3",
      "Askrai Villa 6",
      "Askrai Villa 9",
      "Army Housing Society",
      "Barki Road",
      "Rang Mehal",
      "Gor I",
      "Gor IV",
      "Aurangzeb Block",
      "Tipu Block",
      "Usman Block",
      "Abu Bakar Block",
      "Gulberg 5",
      "CMA Colony",
      "Main Mir Colony",
      "Quaid e Azam Industrial Estate",
      "Salamatpura",
      "Taj Para",
      "Shaikh Zayed Hospital",
      "UCP",
      "Canal Garden",
      "Izmir Town",
      "Canal Park Society",
      "M M Alam Road",
      "Badar Block",
      "Education Town",
      "Jehanzeb Block",
      "Khyber Block",
      "Mehran Block",
      "Neelam Block",
      "Ravi Block",
      "Sutlej Block",
      "Zeenat Block",
      "Fort Villas",
      "Infantry Road",
      "Tufail Road",
      "Munir Road",
      "Zaman Colony",
      "Valencia Town Block A1",
      "Valencia Town Block C",
      "Valencia Town Block H",
      "Valencia Town Block K1",
      "Bahria Town",
      "Eden Canal Villas",
      "Doctors Society",
      "Awan Town",
      "Saidpur",
      "Ichhra",
      "Riwaz Garden",
      "Sanda Kalan",
      "Bilal Gang",
      "Ravi Road",
      "Usman Ganj",
      "Badami Bagh",
      "Star Town",
      "Khudad Town",
      "Shalimar Link Road",
      "Mughal Pura",
      "Samia Town",
      "Guldasit Colony",
      "Mustafa Bad",
      "Canal Road",
      "Engineer Cooperative Society",
      "PCSIR Housing Society",
      "Jinnah Hospital",
      "New Garden Town",
      "Fc College",
      "PIA Society",
      "Shama Colony",
      "Model Town",
      "Township",
      "Baba Farid Colony",
      "Green Town",
      "Punjab Govt Employs Coparative Society",
      "Lalzar Colony",
      "Main Khayaban Road",
      "Nasheman Iqbal Housing Scheme",
      "Wapda Town",
      "Anar Kali",
      "Davis Road",
      "Dharampura",
      "Lakshmi Chowk",
      "Wapda House",
      "Ganga Ram Hospital",
      "Gulberg 1",
      "Firozpur Road",
      "Madina Colony",
      "Chungi Amer Sadhu",
      "Youhna Bad",
      "Alfalah Town",
      "Super Town",
      "Sui Gas Society",
      "DHA 2",
      "DHA 5",
      "DHA 8",
      "Gohawa",
      "Askrai Villa 1",
      "Askrai Villa 4",
      "Askrai Villa 7",
      "Askrai Villa 10",
      "Eden Avenue",
      "Paragon City",
      "Architects Engineers Society",
      "Gor II",
      "Gor V",
      "Aibak Block",
      "Shersha Block",
      "Ali Block",
      "Ahmed Block",
      "Gulberg 4",
      "Saint John Park",
      "Upper Mall Scheme",
      "Kainchi",
      "Sarwar Road",
      "Moon Market",
      "Gulshan Block",
      "Muhafiz Town",
      "Tricon Valley",
      "Iqbal Avenue",
      "Main Gulberg Boulevard",
      "Asif Block",
      "Chenab Block",
      "Huma Block",
      "Kamran Block",
      "Mamdoot Block",
      "Mustafa Town",
      "Nishtar Block",
      "Rachna Block",
      "Sikandar Block",
      "Makkah Colony",
      "Bridge Colony",
      "Khursheed Alam Road",
      "Lawrence Road",
      "R A Bazaar",
      "LDA Colony",
      "Valencia Town Block A2",
      "Valencia Town Block F",
      "Valencia Town Block H1",
      "EME DHA Society",
      "Eden Homes",
      "Thokar Niaz Baig",
      "Canal Breeze",
      "Sabzazar",
      "Wahdat Colony",
      "Band Road",
      "Islam Pura",
      "Amin Park",
      "Data Nagar",
      "Misri Shah",
      "Darbar Gurreh Shah",
      "Wapda Colony",
      "Mahmood Booty Ring Road",
      "Ghousia Colony",
      "Nabi Pura",
      "Muslima Bad",
      "New PAF Colony",
      "Fortress Stadium",
      "Canal View Colony",
      "Tech Society",
      "Alpha Co Operative",
      "Allama Iqbal Medical College",
      "Muslim Town",
      "Shah Jamal",
      "Revenue Society",
      "Peco Road",
      "New Mustafa Colony",
      "Kot Lakhpat",
      "Race Course Town",
      "PCSIR Society",
      "Raiwind Road",
      "West Wood Colony",
      "Opf Colony",
      "Tariq Garden",
      "Khyaban E Amin",
      "Mall Road",
      "Garhi Shahu",
      "Mayo Hospital",
      "Punjab University Old Campus",
      "Jail Road",
      "Race Course Park Surrounding Area",
      "Gulberg 2",
      "Askari Colony",
      "Walton Road",
      "Awan Market",
      "Abdalian Housing Society",
      "Chararrd Village",
      "Rehman Garden",
      "State Life Society",
      "DHA 3",
      "DHA 6",
      "Lidhar",
      "Airport Road",
      "Askrai Villa 2",
      "Askrai Villa 5",
      "Askrai Villa 8",
      "Askrai Villa",
      "Eden View",
      "LUMS",
      "Civic Center",
      "Gor III",
      "Tariq Block",
      "Babar Block",
      "Atta Turk Block",
      "Garden Block",
      "Iqbal Ave Housing Society",
      "Ferozpur Road",
      "Saddar",
      "Temple Road",
      "K B Society",
      "Taj Bagh",
      "Nizam Block",
      "Shaukat Khanum Hospital",
      "LDA Avenue",
      "Jubli Town",
      "Canal Bank",
      "Falcon Complex",
      "Multan Road",
      "College Block",
      "Hunza Block",
      "Karim Block",
      "Maraghzar Colony",
      "Nargis Block",
      "Pak Block",
      "Raza Block",
      "Umer Block",
      "Khuda Buksh",
    ],
  },
  {
    name: "Faisalabad",
    sublocation: [
      "Madina Town",
      "Ayub Agricultural Research Institute",
      "Chak 207 GB",
      "Millat Colony",
      "Chak 583 GB",
      "Nishat Abad",
      "Chak 59jb",
      "Noorpur",
      "Chak 66 GB",
      "Peoples Colony No.2",
      "Chak 98/GB",
      "Gangapur",
      "Chak Jhumra",
      "Garh",
      "Dasuha",
      "Ghulam Muhammad Abad",
      "Dich Kot",
      "Jaranwala",
      "Aminpur Bangla",
      "Kanjwani",
      "Rorala Road",
      "Mamu Kanjan",
      "Sahuwala",
      "Millat Town",
      "Samundri",
      "Murid Wala",
      "Sitara Colony",
      "P.A.F. Risalay Wala",
      "Tandlian Wala",
      "Pindi Shiekh Musa",
      "Thjkri Wala",
      "Board Of Education",
      "Khurrian Wala",
      "Buchiana",
      "Chak 229 RB",
      "Burj Mandi",
      "Chak 248 RB",
      "Chak 103 JB",
      "Chak 253 RB",
      "Chak 103 RB",
      "Chak 257 RB",
      "Chak 113 GB",
      "Chak 267 RB",
      "Chak 117 JB",
      "Chak 271 RB",
      "Chak 128 GB",
      "Chak 275 J.B",
      "Chak 16 JB",
      "Chak 353 GB",
      "Chak 189 RB",
      "Chak 433 GB",
      "Chak 199 RB",
      "Chak 447 GB",
      "Other",
    ],
  },
  {
    name: "Rawalpindi",
    sublocation: [
      "Bagh Jamiri",
      "Banda",
      "Bassali",
      "Benahal Pattan",
      "Bhalakhar",
      "Bhall",
      "Chak Beli Khan",
      "Chakrali Budhal",
      "Chakri",
      "Chauntra",
      "Dahgal",
      "Dharyala Sehgal",
      "Durniyan",
      "Hanesar",
      "Haraka",
      "Jabbar Darvesh",
      "Jewra",
      "Jhatta Hathial",
      "Kahuti Bazar",
      "Kalan Basand",
      "Kehrore",
      "Kolian Hameed",
      "Kotli Sattian",
      "Lehri",
      "Lehtrar Bala",
      "Mahuta Mohra",
      "Maira (Rawalpindi)",
      "Mallot Sattian",
      "Manghota Barahmnan",
      "Murree Brewary Rawalpindi",
      "Paryal",
      "Phapril",
      "Pindoori (Chak Bali Khan)",
      "Rawalpindi Attock Oil Company",
      "Rawalpindi Bahria Town (Phase 1, 2, 3, 4)",
      "Rawalpindi Chak Jalal Din",
      "Rawalpindi Chaklala Air Field",
      "Rawalpindi Dhamial Camp",
      "Rawalpindi Fizaia Colony",
      "Rawalpindi General Headquarters",
      "Rawalpindi Gpo",
      "Rawalpindi Gulzar-e-quaid",
      "Rawalpindi High Court",
      "Rawalpindi Judicial Town",
      "Rawalpindi Kohinoor Colony",
      "Rawalpindi Kutchery",
      "Rawalpindi Momin Pura",
      "Rawalpindi Pir Wadhai",
      "Rawalpindi Raja Town",
      "Rawalpindi Satellite Town",
      "Rawalpindi Urdu Bazar",
      "Rawalpindi Westridge",
      "Ruper Kalan",
      "Other",
    ],
  },
  {
    name: "Multan",
    sublocation: [
      "Bahadar Pur",
      "Bahauddin Zakariya University",
      "Basti Malook",
      "Budhla Sant",
      "Chak-379/wb",
      "Dhanot",
      "Galay Wala",
      "Gulgasht Colony",
      "Industrial Estate",
      "Ismailabad",
      "Jalalpur Pirwala",
      "Javed Nagar",
      "Kadirpur Rawan",
      "Khan Bela",
      "Kotali Nijabat",
      "Lar",
      "Makhdum Rashid",
      "Matotli",
      "Multan Army Aviation Base",
      "Multan Fertilizer Project",
      "Multan GPO",
      "Mumtaz Abad",
      "New Multan",
      "Piran Ghaib",
      "Secondary Board",
      "Shujabad",
      "Sikandar Abad",
      "Suraj Miani",
      "Tatepur",
      "Other",
    ],
  },
  {
    name: "Gujranwala",
    sublocation: [
      "Ahmad Nagar",
      "Ali Pur Chatha",
      "Aroop",
      "Botala Sardar Jhanda Singh",
      "Budha Goraya",
      "Dhonkal",
      "Emin Abad",
      "Emin Abad More",
      "Ghakhar",
      "Gondalan Wala",
      "Gujranwala Anwar Industries",
      "Gujranwala Cantt",
      "Gujranwala Climax Abad",
      "Gujranwala Gpo",
      "Gujranwala Peoples Colony",
      "Gujranwala Secondary Board",
      "Hafiz Abad",
      "Jalalpur Nau",
      "Jalil Town",
      "Jhallan",
      "Kalaskey",
      "Kaleke",
      "Kamo Ke",
      "Kassoki",
      "Khanki",
      "Kohlowala",
      "Ladhe Wala Waraich",
      "Mohlanke",
      "Muhaliwala",
      "Naushera Virkan",
      "Nithrike",
      "Nizam Abad",
      "Nizam Pur Gujranwala",
      "Papnakha",
      "Pindi Bhatian",
      "Qasirabad Colony",
      "Qila Didar Singh",
      "Qila Mian Singh",
      "Rasul Nagar",
      "Sadhoke",
      "Soharan Chatha",
      "Sohdra",
      "Sukhe Ke Mandi",
      "Talwandi Rahwali",
      "Tatley Aali",
      "Vaniawala",
      "Wahdat Colony",
      "Wando",
      "Wanike Tarar",
      "Wapda Town",
      "Wazirabad",
      "Other",
    ],
  },
  {
    name: "Hyderabad",
    sublocation: [
      "Badho Kambrani",
      "Badin",
      "Behar Colony Kotri",
      "Bhit Shah",
      "Bulri Shah Karim",
      "Chamber",
      "Chuhar Jamali",
      "Darro",
      "Dewan Sugar Mills Thatta",
      "Dhabeji",
      "Fauji Sugar Mills Khoski",
      "Filter Plant Gharo",
      "Garho",
      "Gharo",
      "Goth Shahnawaz",
      "Hala",
      "Hala Old",
      "Hashimabad",
      "Husri",
      "Hyderabad Cantt.",
      "Hyderabad City",
      "Hyderabad",
      "Jang Shahi",
      "Jati",
      "Jhimpir R.s.",
      "Jhok Sharif",
      "Kario Ghanwar",
      "Khadhan",
      "Khuda Ki Basti",
      "Kinjhar Lake",
      "Kotri",
      "Ladiun",
      "Latifabad",
      "Liaqat Medical College (Jamshoro)",
      "Mansora",
      "Matiari",
      "Matli",
      "Mehran Sugar Mills (Tando Allahyar)",
      "Mirpur Bathoro",
      "Mirpur Sakro",
      "Missan Wadi",
      "Nando Shahar",
      "Nasarpur",
      "New Dambalo",
      "Nooriabad",
      "Oderolal R.s.",
      "Oderolal Village",
      "P.a.f. Badin",
      "Pangrio",
      "Petaro Cadet College",
      "Qasimabad",
      "Railway Crossing Jamshoro",
      "Other",
    ],
  },
  {
    name: "Peshawar",
    sublocation: [
      "Badbher",
      "Badhber Paf Camp",
      "Bara Fort",
      "Chamkani",
      "Daud Zai",
      "Hayatabad  (phase-i)",
      "Hayatabad Phase-ii",
      "Jamrud",
      "Landi Arbab",
      "Landi Kotal",
      "Mashoo Khel",
      "Mathani",
      "Musa Zai",
      "Nasir Bagh",
      "Pak Forest Institute Peshawar",
      "Pakha Ghulam",
      "Pawaka",
      "Peshawar C.t. Training School",
      "Peshawar Education Board",
      "Peshawar",
      "Peshawar Industrial Estate",
      "Peshawar Poly Technical College",
      "Peshawar University",
      "Regi",
      "Sakhi Chashma",
      "Sar Band",
      "Sherkira",
      "Tehkal Bala",
      "Tehkal Payan",
      "Warsak Colony",
      "Yaka Toot",
      "Other",
    ],
  },
  {
    name: "Islamabad",
    sublocation: [
      "Islamabad Aiwan-e-Saddar",
      "Islamabad Allama Iqbal Open University",
      "Islamabad B-block Pak Sectt.",
      "Islamabad Cabinet Block",
      "Islamabad Dha Phase-ii",
      "Islamabad E-9 (Air Hq)",
      "Islamabad F-7 Markaz",
      "Federal Capital Islamabad F-8 Markaz",
      "Islamabad Federal Board",
      "Islamabad G-10 Markaz",
      "Islamabad G-5 Foreign Office",
      "Islamabad G-8/Markaz",
      "Islamabad G-9/Markaz",
      "Islamabad Gpo",
      "Islamabad Hajj Complex",
      "Islamabad I-10/Markaz",
      "Islamabad I-8/4",
      "Islamabad National Health Laboratiories",
      "Islamabad Primr Minister Sectt.",
      "Islamabad Quaid-e-Azam University",
      "Islamabad, Model Town Humak",
      "Ali Pur Frash",
      "Bagnial",
      "Bara Kau",
      "Chirah",
      "Golra",
      "Herdogher",
      "Jagiot, Islamabad",
      "Kirpa, Islamabad",
      "Kuri, Islamabad",
      "Lohi Bher, Islamabad",
      "Malpur, Islamabad",
      "Mara Jaffar, Islamabad",
      "Nilore, Islamabad",
      "Noorpur Shahan, Islamabad",
      "Pakistan Town (korang Town)",
      "Rawal Town, Islamabad",
      "Rewat",
      "Saree Chowk",
      "Shah Allah Ditta",
      "Sihala",
      "Sohan",
      "Tarlai Kalan",
      "Tarnol",
      "Other",
    ],
  },
  {
    name: "Quetta",
    sublocation: [
      "Ahmadoon",
      "Ahmedwal",
      "Ali Town",
      "Baleli",
      "Barshore",
      "Bostan",
      "Chaman",
      "Dalbandin",
      "Digari",
      "Habibabad",
      "Hazar Gangi",
      "Hurram Zai",
      "Infantory School",
      "Khanozai",
      "Kharan",
      "Killa Abadulllah",
      "Killi Abdul Rehmanzai",
      "Killi Abdur Rehman Zai",
      "Killi Tirkha",
      "Killi Verchoom",
      "Kuchlak",
      "Ladgasht",
      "Manzari",
      "Nasirabad",
      "Nawan Killi",
      "Nokundi",
      "Pishin",
      "Quetta Air Port",
      "Quetta GPO",
      "Samungali",
      "Saranan",
      "Sariab",
      "Sariab Road",
      "Satellite Town Quetta",
      "Sorange",
      "Staff College Quetta",
      "Ziarat",
      "Other",
    ],
  },
  {
    name: "Sargodha",
    sublocation: [
      "Ahmed Pur",
      "Alamabad",
      "Alipur Noon",
      "Astana-e-Fazal",
      "Bhabra",
      "Bhagtan Wala",
      "Bhalwal",
      "Bhera",
      "Bhuleer Chak 119",
      "Bulland Hill",
      "Chak 10 M.L",
      "Chak 111 SB",
      "Chak 29 S.B",
      "Chak 34 N.B",
      "Chak 36 S.B",
      "Chak 46 S.B",
      "Chak 64 S.B",
      "Chak 86 S.B",
      "Chak 88 S.B",
      "Chak Ram Das",
      "Dharima",
      "Farooka",
      "Gondal (SGD)",
      "Hazoorpur",
      "Hujjan",
      "Hyderabad Town (SGD)",
      "Jahanabad",
      "Jhawrian",
      "Kallas Sharif",
      "Kandan",
      "Kirana Hill",
      "Kot Moman",
      "Lalliani",
      "Manzoor Hayat Colony Bhalwal",
      "Miani",
      "Midh Ranjha",
      "Moazam Abad",
      "Mori",
      "Nihang",
      "Noon Sugar Mills Bhalwal",
      "Phular Wan",
      "Punja",
      "Sahiwal (Sgd)",
      "Sail Sharif",
      "Sargodha Cantt",
      "Sargodha GPO",
      "Sargodha P.A.F Base",
      "Sargodha Secondary Board",
      "Sargodha Taxtile Mills",
      "Shah Nikdar",
      "Shah Pur City",
      "Shah Pur Sadar",
      "Shaheenabad",
      "Sial Chowk",
      "Sillan Wali",
      "Tangowali",
      "Uttian",
      "Wijh",
      "Other",
    ],
  },
  {
    name: "Sialkot",
    sublocation: [
      "Kotli Loharan West",
      "Begowala",
      "Kullowal",
      "Bhirth",
      "Lengriali",
      "Bhopal Wala",
      "Malkey Klan",
      "Bhoth",
      "Mandir Syedan",
      "Chaprar",
      "Maraki Wal",
      "Chawinda",
      "Marala",
      "Chobara",
      "Mehrajke",
      "Dallowali",
      "Mitran Wali",
      "Daska",
      "Mundeke Goraya",
      "Fateh Garh",
      "Nowshera Kakezian",
      "Ghartal",
      "Pasrur",
      "Ghunike",
      "Phuklian",
      "Gohadapur",
      "Rajra Garhi",
      "Gondal",
      "Sahowala",
      "Jamki",
      "Saidpur",
      "Jatheki",
      "Sambrial",
      "Kalas Wala",
      "Satrah",
      "Kapurowali",
      "Cantt",
      "Khan Pur Syedan",
      "Small Industries Estate",
      "Kharota Syedan",
      "Ugoke",
      "Kotli Behram",
      "Wadala Sandhuan",
      "Kotli Loharan East",
      "Other",
    ],
  },
  {
    name: "Bahawalpur",
    sublocation: [
      "AHMAD PUR EAST",
      "ASHRAF SUGAR MILLS BAHAWALPUR",
      "BAHAWALPUR CANTT",
      "BAHAWALPUR GPO",
      "BAHAWALPUR INTERMEDIATE SECONDRY BOARD",
      "CHAK 117/D.B",
      "CHANI GOTH",
      "CHHONAWALA",
      "DERA BAKHA",
      "DUNYA PUR",
      "HASIL PUR MANDI",
      "HATHEJI",
      "HEAD RAJKAN",
      "JAMALPUR",
      "KAHROR PAKKA",
      "KHAIRPUR TAMIWALI",
      "KHANQAH MUBARIK",
      "KOTLA MUSA KHAN",
      "KUTABPUR",
      "LODHRAN",
      "MUBARIKPUR",
      "NOORPUR NAURANGA",
      "PALLAH",
      "PANJNAD",
      "QAIM PUR",
      "SADIQ GARH PALACE",
      "SADIQ PUBLIC SCHOOL BAHAWALPUR",
      "SAHIWALA",
      "SAMASATTA",
      "UCH SHARIF",
      "YAZMAN",
      "Other",
    ],
  },
  {
    name: "Sukkur",
    sublocation: [
      "ADIL PUR",
      "ARAIN ROAD",
      "BABARLOI",
      "BAGARJI",
      "BERRARI",
      "DAD LAGHARI",
      "DHARKI",
      "FERTILIZER FACTORY DHARKI",
      "GHOTKI",
      "JARWAR",
      "KANDIRA",
      "KHAMBARA",
      "KHANPUR MAHAR",
      "MIRPUR MATHELO",
      "PAF AIRPORT",
      "PAK SAUDI FERTILIZAR MIRPUR MATHELO",
      "PANNU AKIL CANTT.",
      "PANO AKIL",
      "ROHRI",
      "ROHRI CEMENT WORKS",
      "SALEH PAT",
      "SARHAD",
      "SUKKUR BOARD OF SECONDARY EDUCATION",
      "SUKKUR GPO",
      "THRACHANI",
      "UBAURO",
      "Other",
    ],
  },
  { name: "Kandhkot", sublocation: ["others"] },
  { name: "Shekhupura", sublocation: ["others"] },
  {
    name: "Mardan",
    sublocation: [
      "BABU ZAI",
      "BAIZU KHARKI",
      "BAKHSHALI",
      "DAGGAR",
      "DOBIAN",
      "DOGAI",
      "GARHI KAPURA",
      "GHARIBABAD",
      "GHULAM ISHAQ KHAN INSTITUTE",
      "GOHKEER",
      "GUJAR GARHI",
      "GUJRAT (MARDAN)",
      "HATHIAN",
      "ISMAILA",
      "JALALA",
      "JAMAL GARHI",
      "JEWAR",
      "KALU KHAN",
      "KATLANG",
      "KOGHUZI",
      "KOHI BARMOL",
      "LUND KHAWAR",
      "MARDAN GPO",
      "MARDAN SUGAR RESEARCH INSTITUTE",
      "MASTUGE",
      "MAYAR",
      "MERA GRAM",
      "MOHABATABAD",
      "NAGAR (CHITRAL)",
      "NAWAN KILLI",
      "PALO DHERI",
      "PANJPIR",
      "PARA BEG",
      "PIR BABA",
      "PLAI",
      "RUSTAM",
      "SATTAR KHAN COLONY",
      "SAWAL DHER",
      "SHAH BAZ GARHI",
      "SHAH MANSOOR",
      "SHER GARH",
      "SHEWA",
      "SHOT KHARA",
      "TAKKAR",
      "TAZAGRAM",
      "TOR WARSAK",
      "TORU",
      "UMARABAD",
      "Other",
    ],
  },
  {
    name: "Gujrat",
    sublocation: [
      "ADOWAL",
      "AURANGABAD",
      "AWAN SHARIF",
      "BAISA KALAN",
      "BARNALI",
      "BHADDAR",
      "BHAGOWAL KALAN",
      "BHAKHRE WALI",
      "BHOTA",
      "BULANI",
      "BURCH BASUHA",
      "BUZURANG WAL",
      "CHAK KAMALA",
      "CHAK MUHAMMAD",
      "DAULAT NAGAR",
      "DEVNA MANDI (BASCO)",
      "DHODHA SHARIF",
      "DHORIA",
      "DULLAN WALA",
      "FATEH PUR",
      "GOTRIALA",
      "GUJRAT G.P.O.",
      "GULIANA",
      "HAJIWALA",
      "JALAL PUR JATTAN",
      "JAURAH",
      "JOKALIAN",
      "KAKRALI",
      "KARARIWALA KALAN",
      "KARIANWALA",
      "KAWANKH",
      "KHADRIALA",
      "KHARIAN CANTT",
      "KHARIAN CITY",
      "KHOHAR",
      "KHOKHAR GHARBI",
      "KOTLA",
      "KUNJAH",
      "LAKHAN WAL",
      "LALA MUSA",
      "LANGAY",
      "MADINA",
      "MAKIANA",
      "MALAKPUR",
      "MALKA",
      "MAND ",
      "MANGOWAL",
      "MOHRI",
      "MOINUDDIN PUR",
      "NAGRIAN",
      "NATIONAL WOOD INDUSTRIES LALA MUSA",
      "PERO SHAH",
      "SAADAT PUR",
      "SABOWAL",
      "SAMRALA",
      "SARAI ALAMGIR",
      "SARIYA",
      "SEHNA",
      "SHADIWAL",
      "SHEIKH PUR",
      "SIDH",
      "SIKARIALI",
      "SOBOOR",
      "SURAKHPUR",
      "TANDA",
      "THUTHA RAI BAHADAR",
      "Other",
    ],
  },
  {
    name: "Larkana",
    sublocation: [
      "ARZI BHUTTO",
      "BADAH",
      "BAHRAM",
      "BAKRANI VILLAGE",
      "BANGUL DERO",
      "BER",
      "BERO CHANDIO",
      "CADIT COLLEGE, LARKANA",
      "CHAK YANI",
      "CHANDKA MEDICAL COLLEGE LARKANA",
      "DOKRI",
      "GAJI KHUHAWAR",
      "GARELO",
      "GATHER",
      "GHARI KHUDA BUX BHUTTO",
      "HAYDER JATOI",
      "KAMBAR",
      "KHAIRPUR JOSO",
      "LALU RAUNK",
      "LARKANA GPO",
      "LASHARI",
      "MENA",
      "MIRAN MACHI",
      "MIRO KAHN",
      "MOENJODARA",
      "NAODERO",
      "NASIRABAD LARKANA",
      "PIR BUX BHUTTO",
      "RATO DERA",
      "SHAHDAD KOT",
      "WAGGAN",
      "WARAH",
      "Other",
    ],
  },
  {
    name: "Kasur",
    sublocation: [
      "BHAI PHERU",
      "CHHANGA MANGA",
      "CHUNIAN",
      "CLARKABAD",
      "ELLAHABAD",
      "GANDA SINGH WALA",
      "JAMBER KALAN",
      "KANGANPUR",
      "KASUR G.P.O",
      "KHUDIAN",
      "KOT RADHA KISHAN",
      "MUSTAFABAD KASUR",
      "PATTOKI",
      "RAJA JANG",
      "ROBBY TAXTILE MILL KASUR",
      "TALWANDI",
      "USMAN WALA",
      "WAN RADHA RAM",
      "Other",
    ],
  },
  {
    name: "Rahim Yar Khan",
    sublocation: [
      "AHMADPUR LAMA",
      "ALLAH ABAD",
      "BAGHO BAHR",
      "BANGLA MANTHAR",
      "BHONG",
      "CHACHRAN SHARIF",
      "CHAK 102/P",
      "FEROZA",
      "HYSONS SUGAR MILLS JETHA BHUTTA",
      "IQBALABAD",
      "JAMAL DIN WALI",
      "KHAN BELA",
      "KHAN PUR",
      "KOT SOMABA",
      "KOT SUBZAL",
      "LIAQAT PUR",
      "MACHI GOTH",
      "MIAN WALI QURESHIAN",
      "Other",
    ],
  },
  {
    name: "Sahiwal",
    sublocation: [
      "ADDA GAMBEER",
      "AL-JAMIA",
      "ARIF WALA",
      "CHAK 119/13-AL",
      "CHAK 120/13-AL",
      "CHAK 120/9-L",
      "CHAK 145/9-L",
      "CHAK 168/9-L",
      "CHAK 85/6 R (KOT KHADIM ALI SHAH)",
      "CHAK 90/9-L",
      "CHAK 91/6-R",
      "CHAK BEDI",
      "CHAK NO.73/5-L (MOGHAL)",
      "CHAK SHAFI",
      "CHAK-5/11L",
      "CHAL NO.127/EB",
      "CHICHAWATNI",
      "FARID NAGAR",
      "FARID TOWN SAHIWAL",
      "GHAZI ABAD",
      "HARAPPA CITY",
      "HARAPPA RAILWAY STATION",
      "IQBAL NAGAR",
      "KASSOWAL",
      "MALKA HANS",
      "NOOR SHAH",
      "PAK PATTAN SHARIF",
      "QABULA",
      "SAHIWAL GOVERNMENT COLLEGE",
      "SAHIWAL GPO",
      "SHEIKH FAZAL",
      "Other",
    ],
  },
  {
    name: "Okara",
    sublocation: [
      "AKHTAR ABAD",
      "ANWAR SHAEED COLONY RENALA KHURD",
      "BASIR PUR",
      "CHAK 53/2-L",
      "DEPALPUR",
      "GOGERA",
      "HAVELI LAKKHA",
      "HUJRA",
      "JABOKA",
      "MANDI AHMED ABAD",
      "MILITARY FARMS OKARA",
      "OKARA AMMUNITION DEPOT",
      "OKARA CANTONMENT",
      "OKARA GPO",
      "RENALA KHURD",
      "SHER GARH",
      "SULEMANKI HEAD WORKS",
      "Other",
    ],
  },
  {
    name: "Wah Cantonment",
    sublocation: [
      "AHATA FAROOQIA",
      "HEAVY MECHANICAL COMPLEX TAXILA",
      "LALA RUKH WAH CANTT",
      "LALAZAR COLONY WAH",
      "P.M.O COMPLEX WAH",
      "PAKISTAN ORDINANCE FACTORY GUDWAL",
      "RAWALPINDI P.M.O COMPLEX",
      "SADDAT COLONY",
      "TAXILA",
      "TAXILA CANTT.",
      "WAH",
      "WAH CANTT. G.P.O.",
      "WAH CEMENT WORKS",
      "WAH WEST PARK",
      "Other",
    ],
  },
  {
    name: "Dera Ghazi Khan",
    sublocation: [
      "BARTHI",
      "BASTI BUZDAR",
      "BASTI MALANA",
      "BUGHAL CHAR",
      "CHOTI",
      "D.G KHAN SECONDARY BOARD",
      "D.G.KHAN CEMENT FACTORY",
      "DAJAL",
      "DERA GHAZI KHAN GPO",
      "FORT MUNROO",
      "JALBANI",
      "JAM PUR",
      "JHOKE UTRA",
      "KALA",
      "KHYABAN-E-SARWAR",
      "KOT CHUTTA",
      "KOT QAISRANI",
      "LATRA",
      "MANA",
      "MANGROTHA",
      "MITHAN KOT",
      "MUHAMMAD PUR",
      "NARI",
      "NUTKANI",
      "RAJAN PUR",
      "RETRA",
      "ROJHAN",
      "SAKHI SARWAR",
      "SAMINA",
      "SHADAN LUND",
      "SHAH SADDAR DIN",
      "SOKAR",
      "TAUNSA SHARIF",
      "TIBBI QAISRANI",
      "Other",
    ],
  },
  { name: "Mingora", sublocation: ["Other"] },
  {
    name: "Mirpur Khas",
    sublocation: [
      "CHACHRO",
      "CHHOR",
      "DHORO NARO",
      "DIGRI",
      "DIPLO",
      "ISLAM KOT",
      "JHUDO",
      "KHOKRAPAR",
      "KOT GUHLAM MOHAMMAD",
      "KOT MIRJAN MUHAMMAD",
      "KUNRI",
      "MIRPUR KHAS GPO",
      "MIRWAH GORCHANI",
      "MITHI",
      "MUHAMMAD SALAM PALLI",
      "NABI SIR ROAD",
      "NAGAR PARKAR",
      "NAU KOT",
      "NEW CHHOR",
      "PITHARO",
      "SAMAR ROAD",
      "SAMARO",
      "SATELITTE TOWN MIRPUR KHAS",
      "SHADI PAL",
      "TALHI",
      "TANDO JAN MUHAMMAD",
      "UMAR KOT",
      "Other",
    ],
  },
  { name: "Chiniot", sublocation: ["Other"] },
  {
    name: "Nawabshah",
    sublocation: [
      "AGRICULTUR INSTITUTE NAWABSHAH",
      "AQIL SHAH",
      "BANDHI",
      "BHIRIA CITY",
      "BHIRIA ROAD",
      "BHORTI",
      "BUCHARI",
      "DARBELO",
      "DARYA KHAN MARI",
      "DAULATPUR",
      "DAUR",
      "GHARGOCHHO",
      "GOTH CHAUDHARY SHAH NAWAZ",
      "GUPCHANI",
      "HABERI",
      "JAM SAHIB",
      "KALHORA",
      "KHAN WAHAN",
      "KOTRI KABIR",
      "LAKHA ROAD",
      "LALBANI",
      "MAHRABPUR",
      "MEHRAN UNIVERSITY OF ENGINEERING",
      "MITHIANI",
      "MOHABAT DERO",
      "MORO",
      "MUBBARIK ALI BURIRO",
      "NAUSHERO FEROZ",
      "NAWABSHAH GPO",
      "NEW JATOI",
      "NOOR JHANIAN",
      "NUSRAT 60 MILE MORI",
      "PADIDAN",
      "PADIDAN TOWN",
      "PHUL",
      "QAMARABAD",
      "QAZI AHMED",
      "SADOJA",
      "SAKRAND",
      "SHADI KHAN CHANDIO",
      "TANDO MIR ALI",
      "THARU SHAH",
      "TUNIA BAGA SHAH",
      "Other",
    ],
  },
  { name: "Kamoke", sublocation: ["Other"] },
  { name: "Burewala", sublocation: ["Other"] },
  {
    name: "Jhelum",
    sublocation: [
      "ADRANA",
      "ALLIANCE TEXTILE MILLS",
      "BAKRALA",
      "BANGIAL",
      "BARA GRAN",
      "BARAGOWAH",
      "BARAL COLONY",
      "BILAL TOWN",
      "BISHAN DORE",
      "BUDHAIR",
      "CHAK AKKA",
      "CHAK DAULAT",
      "CHAK JANI",
      "CHAKRI",
      "CHOTALA",
      "DANDOT RAILWAY STATION",
      "DHAIWAL",
      "DHARIALA JALAP",
      "DHOKE BIDDER",
      "DHUDHI THALL",
      "DIAL",
      "DINA",
      "DIWANI HAZOORI",
      "DOMELI",
      "GARH MAHAL",
      "GHARIBWAL CEMENT",
      "HARAN PUR",
      "JALAL PUR SHARIF",
      "JAMARGHAL",
      "JAMMU KASHMIR MUHAJIR COLONY",
      "JANDALA",
      "JHELUM G.P.O.",
      "KAKRALA",
      "KALA",
      "KALA GUJRAN",
      "KHALAS PUR",
      "KHEWRA",
      "KHUKHA",
      "KUNDWAL",
      "LEHRI",
      "LILLA",
      "MAIRA (JHELUM)",
      "MANGLA CANTT",
      "NAGIAL",
      "NAGIAL CHAMKOWN VALLEY",
      "PADHRI",
      "PARI DARWEZA",
      "PIANANWAL",
      "PIND DADAN KHAN",
      "PINDI SAIDPUR",
      "ROHTAS",
      "SAGRI",
      "SANGHOI",
      "SAROBA",
      "SAUWAL",
      "SOHAWA",
      "SURG DHAN",
      "TAHLIAN WALA",
      "TARKAI",
      "TOBAH",
      "TOOR",
      "WAGH",
      "Other",
    ],
  },
  { name: "Sadiqabad", sublocation: ["Other"] },
  {
    name: "Khanewal",
    sublocation: [
      "ABDUL HAKIM",
      "CHAK 136/10-R",
      "CHAK 138/10 R",
      "HANUMAN GARH",
      "JAHANIA",
      "KABIR WALA",
      "KACHA KHUH",
      "KHANEWAL AMMUNITION DEPOT",
      "KHANEWAL GPO",
      "KOHIWALA",
      "KOT ALLAH SINGH",
      "KUKKAR HATTA",
      "MAHNI SIAL",
      "MAKHDOOMPUR PHOHARAN",
      "MIAN CHANNU",
      "MIAN CHANNU RAILWAY STATION",
      "PEEROWAL",
      "PUNJA KASSI",
      "PUNJAB SMALL INDUSTRY",
      "SARAI SIDHU",
      "TALAMBA",
      "THATHA SADIQABAD",
      "Other",
    ],
  },
  { name: "Hafizabad", sublocation: ["Other"] },
  {
    name: "Kohat",
    sublocation: [
      "ALIZAI",
      "BANDA DAUD SHAH",
      "BILLI TANG",
      "DAGAR NARI",
      "DARA ADAM KHEL",
      "DOABA",
      "GHUNDI MIR KHAN",
      "HABIB ABAD",
      "HANGU",
      "HANGU POLICE TRAINING SCHOOL",
      "KAHI",
      "KOHAT BOARD OF EDUCATION",
      "KOHAT CADET COLLEGE",
      "KOHAT GPO",
      "KOHAT GUNNERS LINE",
      "KOHAT J.D.M.T.MILLS",
      "KOHAT OFFICERS TRAINING SCHOOL",
      "KOHAT P.A.F.",
      "KOHAT POLICE RECRUIT TRAINING CENTRE",
      "KOHAT SATELLITE TOWN",
      "LACHI",
      "NARYAB",
      "NASRAT KHEL",
      "PARACHINAR",
      "RAISAN",
      "SADDA",
      "SAROZAI",
      "SENI GUMBAT",
      "SHAKAR DARA",
      "SHER KOT",
      "SURGUL",
      "TERI",
      "THULL CITY",
      "THULL FORT",
      "TOGH BALA",
      "TOGH SARAI",
      "USTER ZAI PAYAN",
      "ZARGERI",
    ],
  },
  {
    name: "Jacobabad",
    sublocation: [
      [
        "AMMUNITION DEPOT KASHMORE",
        "BUXAPUR",
        "GARHI KHAIRO",
        "GHOUS PUR",
        "GHULAM KHAN DHANI",
        "GIDDU BARRAGE",
        "JACOBABAD GPO",
        "KANDHKOT",
        "KASHMOR COLONY",
        "KASHMORE",
        "MIRPUR BURIRO",
        "TANGWANI",
        "THUL",
        "Other",
      ],
    ],
  },
  {
    name: "Shikarpur",
    sublocation: [
      "CHAK",
      "DAKHAN",
      "GARI YASIN",
      "KARAM PUR",
      "KHAN PUR (SHIKARPUR)",
      "LAKHI GHULAM SHAH",
      "MADIJI",
      "RUK",
      "SHIKARPUR GPO",
      "SULTAN KOT",
      "Other",
    ],
  },
  {
    name: "Muzaffargarh",
    sublocation: [
      "AHSAN PUR",
      "ALI PUR",
      "BASIRA",
      "BET MIR HAZAR KHAN",
      "BHUTTA PUR",
      "CH0WK SARWAR SHAHEED",
      "DARAIN",
      "DERA DIN PANAH",
      "DOABA",
      "FAZAL GARH ",
      "FAZAL NAGAR",
      "GAS TARBINE POWER MUZAFFARGARH",
      "GUJRAT (MUZAFFARGARH)",
      "JATOI",
      "KHAIRPUR SADAT",
      "KHAN GARH",
      "KHANPUR SHUMALI",
      "KOT ADU",
      "MEHMOOD KOT ",
      "MISALI MIDDLE PUBLIC SCHOOL PIR JIHANIA",
      "MONDKA",
      "MUZAFFARGARH GPO",
      "QURESHI",
      "RANG PUR",
      "ROHILAN WALI",
      "SHAH JAMAL",
      "SHEHAR SULTAN",
      "SINAWAN",
      "SIT PUR",
      "SULTAN COLONY",
      "THARMAL POWER STATION MUZAFFARGARH ",
      "Other",
    ],
  },
  { name: "Khanpur", sublocation: ["Other"] },
  { name: "Gojra", sublocation: ["Other"] },
  { name: "Bahawalnagar", sublocation: ["Other"] },
  {
    name: "Abbottabad",
    sublocation: [
      "ABBOTTABAD GPO",
      "ABBOTTABAD PUBLIC SCHOOL",
      "AYUB MEDICAL COLLEGE ABBOTTABAD",
      "AYUBIA",
      "BAGAN",
      "BAGNOTAR",
      "BIRAN GALI",
      "CHAMATTI",
      "CHAMYALI",
      "CHANDO MAIRA",
      "CHANGLA GALI ",
      "DALOLA",
      "DHAMTAUR",
      "DUNGA GALI",
      "GAMANG",
      "GAMBEER",
      "HALLI",
      "HAVELIAN",
      "HAVELIAN AMMUNATION DEPOT ",
      "JARRAL",
      "JHANGI",
      "KAKUL",
      "KALA BAGH (HAZARA)",
      "KHAIRA GALI",
      "KUTHIALA",
      "LORA",
      "MAIRA BALA",
      "MANDIAN",
      "NAGRI BALA",
      "NAGRI TOTLIAL",
      "NAMLI MAIRA",
      "NARA",
      "NATHIA GALI",
      "NAWAN SHAHR",
      "PAK ORDINANCE FACTORIES HAVILIAN",
      "PIND KARGO KHAN",
      "QALANDERABAD",
      "RAJOYA",
      "RICHH BHAN",
      "SATURA",
      "SHEIKHUL BANDI",
      "SHERWAN",
      "THANDAYANI ",
      "THARYATI",
      "TOBA CAMP",
      "Other",
    ],
  },
  { name: "Muridke", sublocation: ["Other"] },
  { name: "Pakpattan", sublocation: ["Other"] },
  {
    name: "Khuzdar",
    sublocation: [
      "BASIMA",
      "BELA",
      "BUET ",
      "CADIT COLLEGE MUSTUNG",
      "GADANI",
      "HUB CHOWKI",
      "KALAT",
      "KARAKH",
      "KHUZDAR CANTT.",
      "KHUZDAR G.P.O.",
      "MANOCHAR",
      "MASHKEY",
      "MASTUNG",
      "MASTUNG ROAD",
      "MIANI BEACH",
      "NICHARA",
      "PIDRAN ",
      "SOMMIANI (WINDER)",
      "SORAB",
      "UMERABAD GIDDER",
      "UTHAL",
      "WADH",
      "ZEHRI ",
      "Other",
    ],
  },
  { name: "Jaranwala", sublocation: ["Other"] },
  { name: "Chishtian", sublocation: ["Other"] },
  { name: "Daska", sublocation: ["Other"] },
  { name: "Mandi Bahauddin", sublocation: ["Other"] },
  { name: "Ahmadpur East", sublocation: ["Other"] },
  { name: "Kamalia", sublocation: ["Other"] },
  { name: "Tando Adam", sublocation: ["Other"] },
  {
    name: "Khairpur",
    sublocation: [
      "CHUNDIKO",
      "KHAIR PUR GPO",
      "PIRYALO",
      "SORAH",
      "TANDO MIR ALI",
      "AGRA",
      "AHMED PUR",
      "BUZDAR",
      "CHANG",
      "CONSOLIDATED SUGAR MILLS RANI PUR",
      "F.S.MILLS GAMBAT",
      "GAMBAT",
      "HINGORAJA",
      "KHURRA",
      "KOT DIGI",
      "KUMB",
      "MIRWAH",
      "PRI JO GOTH",
      "RANI PUR",
      "SETHARJA",
      "SOBHO DERA",
      "THEHRI",
      "Other",
    ],
  },
  {
    name: "Dera Ismail Khan",
    sublocation: [
      "BILOT",
      "CHISHMA RIGHT BANK CANAL D.I KHAN",
      "CHOUDHWAN",
      "D.I KHAN POLYTECHNICAL INSTITUTE",
      "D.I KHAN AGRICULTURAL RESEARCH CENTER",
      "DARABAN",
      "DARAZINDA",
      "DERA ISMAIL KHAN GPO",
      "DERA TOWN SHIP",
      "DIN PUR",
      "FORT IQBAL GARH",
      "GOMAL UNIVERSITY NEW CAMPUS",
      "KACHAMALI KHEL",
      "KACHI PAIND KHAN",
      "KIRI SHAMOZAI",
      "KIRRI KHAISOR",
      "KOT JAI",
      "KULACHI",
      "MANDHARA",
      "MURYALI",
      "MUSA ZAI",
      "PAHARPUR",
      "Other",
    ],
  },
  {
    name: "Vehari",
    sublocation: [
      "BUREWALA",
      "BUREWALA KATCHEHRY",
      "CHOWK METHLA",
      "DAWOOD ABAD",
      "DILAWAR FARM SARGANA",
      "DOKOTA",
      "GAGGO",
      "GARHA MORE",
      "JALLA JIM",
      "KARAMPUR",
      "LUDDAN ",
      "MACHHIAN WALA",
      "MAILSI",
      "MAILSI COLONY",
      "MITRU",
      "SARDAR PUR JHANDEER",
      "TIBA SULTANPUR",
      "VEHARI GPO",
      "VEHARI PEOPLES COLONY",
      "Other",
    ],
  },
  {
    name: "Nowshera",
    sublocation: [
      "ADAMJEE PAPER BOARD MILLS NOWSHERA",
      "AKBAR PURA",
      "AKORA KHATTAK",
      "ALLAH BAKHASH COLONY",
      "AZA KHEL BALA",
      "AZA KHEL PAYAN",
      "BANDA MOHIB",
      "BANDA SHEIKH ISMAIL",
      "CHERAT",
      "DAGAI BANDA",
      "DAK ISMAIL KHEL",
      "FEROZ SONS NOWSHERA",
      "JALLOZAI",
      "KHAIR ABAD",
      "KHESHKI PAYAN",
      "MANKI SHARIF",
      "MISRI BANDA",
      "Other",
    ],
  },
  {
    name: "Dadu",
    sublocation: [
      "BHAN SAEEDABAD",
      "BUBAK",
      "DADU GPO",
      "DADU SUGAR MILL (PIARO GOTH)",
      "FAREEDABAD",
      "JOHI",
      "KHAIRPUR NATHAN SHAH",
      "KHANPUR JUNEJO",
      "MEHAR",
      "PHULJI",
      "RADHAN",
      "SEHWAN",
      "SITA",
      "Other",
    ],
  },
  { name: "Wazirabad", sublocation: ["others"] },
  {
    name: "Khushab",
    sublocation: [
      "ADHI KOT",
      "ANGAH",
      "BANDIAL",
      "CHOWK GIROTE",
      "DHADHAR",
      "GIROTE",
      "HADALI",
      "HUSSAIN ABAD",
      "JABBI",
      "JAHLAR",
      "JAMALI",
      "JAUHAR ABAD",
      "KHABBEKKI",
      "KHURA",
      "Other",
    ],
  },
  { name: "Charsada", sublocation: ["Other"] },
  { name: "Swabi", sublocation: ["Other"] },
  { name: "Chakwal", sublocation: ["Other"] },
  {
    name: "Mianwali",
    sublocation: [
      "ALLUWALI",
      "CHAK 4/DB",
      "CHAKRALA",
      "CHAPRI",
      "CHASHMA BARRAGE COLONY MIANWALI",
      "CHHIDROO",
      "DAUD KHEL",
      "DHIBA KAR SIAL",
      "DHURNAKA",
      "DILLEWALI",
      "Other",
    ],
  },
  { name: "Tando Allahyar", sublocation: ["Other"] },
  { name: "Kot Adu", sublocation: ["Other"] },
  { name: "Farooka", sublocation: ["Other"] },
];
const Area = [
  "Accounting & Taxation",
  "Advertising/PR",
  "Agriculture/Fertilizer/Pesticide",
  "Apparel & Fashion",
  "Architecture/Interior Design",
  "Arts/Entertainment",
  "Automotive",
  "Aviation",
  "Banking & Financial Services",
  "BPO",
  "Call Centers",
  "Chemicals",
  "Construction/Cement/Metals",
  "Consultants",
  "Education/Trainings",
  "Electrical/Electronics",
  "Engineering",
  "Event Management",
  "FMCG",
  "Food & Beverages",
  "Government",
  "Health & Fitness",
  "Healthcare/Hospital/Medical Care",
  "Hotels & Restaurants",
  "Human Resources",
  "Importers/Exporters/Distributors",
  "Information Technology",
  "Insurance & Takaful",
  "Law Firms & Legal",
  "Logistics/Supply Chain Management",
  "Manufacturing",
  "Marketing & Advertising",
  "Media/Communication",
  "Mining/Oil & Gas/Petroleum",
  "N.G.O. & Social Services",
  "News & Media",
  "Wholesale",
  "Packaging",
  "Personal care & Services",
  "Pharmaceuticals/Clinical Research",
  "Power & Energy",
  "Project Management",
  "Publishing / Printing",
  "Real Estate & Property",
  "Recruitment & Employment Firms",
  "Retail",
  "Security & Law Enforcement",
  "Shipping & Marine",
  "Telecommunication & ISP",
  "Textiles",
  "Tiles & Ceramics",
  "Travel/Tourism/Transportation",
  "Other",
];
const department = [
  "Accounts & Finance",
  "Administration",
  "Branch Banking",
  "Compliance",
  "Corporate Banking",
  "Distribution & Channel Management",
  "Engineering",
  "Health & Medicine",
  "Human Resource",
  "Information Technology",
  "Marketing",
  "Operations Management",
  "Production",
  "Project Management",
  "Quality Management",
  "Research & Development",
  "Risk Management",
  "Sales",
  "Support",
  "Training & Development",
  "Other",
];
const data = [
  "Assistant Manager",
  "CEO/Country Head/President",
  "Deputy Manager",
  "Entry Level",
  "Executive",
  "Fresh",
  "Manager/Departmental Head",
  "Officer",
  "Professional",
  "Senior Executive",
  "Senior Officer",
  "Team Lead",
  "Vice President/General Manager",
  "Other",
];
const experience = [
  "fresh",
  "1 - 3 Years",
  "3 - 6 Years",
  "6 - 9 Years",
  "9 - 12 Years",
  "12 - 15 Years",
  "15 - 18 Years",
  "18 - 21 Years",
  "21 - 24 Years",
  "24 - 27 Years",
  "27 - 30 Years",
  "Above 30",
];
const education = [
  "Non-Matriculation",
  "Matriculation/O-Levels",
  "Intermediate/A-Levels",
  "Bachelors Degree",
  "Masters Degree",
  "Doctorate Degree",
  "Diploma",
  "Other",
];

// const cardata = [
//   {
//     make: "Suzuki",
//   },
//   {
//     make: "Honda",
//   },
//   {
//     make: "Toyota",
//   },
//   {
//     make: "Nissan",
//   },
//   {
//     make: "Mitsubishi",
//   },
//   {
//     make: "Mazda",
//   },
//   {
//     make: "KIA",
//   },
//   {
//     make: "FAW",
//   },
//   {
//     make: "Fiat",
//   },
//   {
//     make: "Lexus",
//   },
//   {
//     make: "Hyundai",
//   },
//   {
//     make: "BMW",
//   },
//   {
//     make: "Hino",
//   },
//   {
//     make: "Mercedes Benz",
//   },
//   {
//     make: "Audi",
//   },
//   {
//     make: "Austin",
//   },
//   {
//     make: "Bentley",
//   },
//   {
//     make: "Buick",
//   },
//   {
//     make: "Cadillac",
//   },
//   {
//     make: "Changan",
//   },
//   {
//     make: "Chery",
//   },
//   {
//     make: "Chevrolet",
//   },
//   {
//     make: "Chrysler",
//   },
//   {
//     make: "Citroen",
//   },
//   {
//     make: "Classic Cars",
//   },
//   {
//     make: "DFSK",
//   },
//   {
//     make: "Daewoo",
//   },
//   {
//     make: "Daihatsu",
//   },
//   {
//     make: "Daimler",
//   },
//   {
//     make: "Datsun",
//   },
//   {
//     make: "Dodge",
//   },

//   {
//     make: "Ferrari",
//   },
//   {
//     make: "Ford",
//   },
//   {
//     make: "GMC",
//   },
//   {
//     make: "Geely",
//   },
//   {
//     make: "Golden Dragon",
//   },
//   {
//     make: "Golf",
//   },
//   {
//     make: "Hillman",
//   },
//   {
//     make: "Adam",
//   },
//   {
//     make: "Hummer",
//   },
//   {
//     make: "Isuzu",
//   },
//   {
//     make: "Jaguar",
//   },
//   {
//     make: "Jeep",
//   },
//   {
//     make: "Kaiser Jeep",
//   },
//   {
//     make: "Lada",
//   },
//   {
//     make: "Lamborghini",
//   },
//   {
//     make: "Land Rover",
//   },
//   {
//     make: "Lincoln",
//   },
//   {
//     make: "MG",
//   },
//   {
//     make: "MINI",
//   },
//   {
//     make: "Maserati",
//   },
//   {
//     make: "Master",
//   },
//   {
//     make: "Morris",
//   },
//   {
//     make: "Moto Guzzi",
//   },
//   {
//     make: "Oldsmobile",
//   },
//   {
//     make: "Opel",
//   },
//   {
//     make: "Others",
//   },
//   {
//     make: "Peugeot",
//   },
//   {
//     make: "Plymouth",
//   },
//   {
//     make: "Pontiac",
//   },
//   {
//     make: "Porsche",
//   },
//   {
//     make: "Proton",
//   },
//   {
//     make: "Range Rover",
//   },
//   {
//     make: "Renault",
//   },
//   {
//     make: "Rolls Royce",
//   },
//   {
//     make: "Roma",
//   },
//   {
//     make: "Rover",
//   },
//   {
//     make: "Royal Enfield",
//   },
//   {
//     make: "Saab",
//   },
//   {
//     make: "Scion",
//   },
//   {
//     make: "Skoda",
//   },
//   {
//     make: "Smart",
//   },
//   {
//     make: "Sogo",
//   },
//   {
//     make: "Sokon",
//   },
//   {
//     make: "SsangYong",
//   },
//   {
//     make: "Subaru",
//   },
//   {
//     make: "Triumph",
//   },
//   {
//     make: "Vauxhall",
//   },
//   {
//     make: "Volkswagen",
//   },
//   {
//     make: "Volvo",
//   },
//   {
//     make: "Willys",
//   },
//   {
//     make: "Alfa Romeo",
//   },
// ];
// const Suzuki = [
//   {
//     model: "Mehran",
//     versions: [
//       ,
//       "VX Euro II",
//       "VXR Euro II",
//       "VX Euro II (CNG)",
//       "VXR Euro II (CNG)",
//       "VX",
//       "VXR",
//       "VX (CNG)",
//       "VXR (CNG)",
//     ],
//   },
//   {
//     model: "Cultus",
//     versions: [
//       ,
//       "VXL",
//       "VXR",
//       "VXRi",
//       "EURO II",
//       "VXLi",
//       "VXLi (CNG)",
//       "VXRi (CNG)",
//       "Euro II (CNG)",
//       "Limited Edition",
//       "VX",
//       "VXR",
//       "VXL",
//       "VXR (CNG)",
//       "VX (CNG)",
//       "VXL (CNG)",
//     ],
//   },
//   {
//     model: "Alto",
//     versions: [
//       ,
//       "X",
//       "VP",
//       "L",
//       "F",
//       "VP",
//       "G",
//       "F",
//       "E",
//       "G4",
//       "X",
//       "GII",
//       "Memorial of the 30th Birth Anniversary",
//       "EII",
//       "VS",
//       "X",
//       "VP",
//       "E",
//       "G",
//       "VXR",
//       "VX",
//       "VX (CNG)",
//       "VXR (CNG)",
//     ],
//   },
//   {
//     model: "Bolan",
//     versions: [, "VX Euro II", "Cargo Van Euro ll", "VX", "VX (CNG)", "GL"],
//   },
//   {
//     model: "Khyber",
//     versions: [, "GA", "Plus"],
//   },
//   {
//     model: "Alto Eco",
//     versions: [, "ECO-S", "ECO-L"],
//   },
//   {
//     model: "Alto Lapin",
//     versions: [
//       ,
//       "G",
//       "XL",
//       "TL",
//       "X Selection",
//       "10th Anniversary Limited",
//       "G",
//       "G Edition",
//       "L",
//       "SS",
//       "X2",
//       "X",
//       "Mode",
//       "Turbo",
//     ],
//   },
//   {
//     model: "APV",
//     versions: [, "GLX", "GLX (CNG)"],
//   },
//   {
//     model: "Baleno",
//     versions: [, "GLi", "GXi", "JXR", "JXL", "Sport", "GLi P", "GTi 1.6", "GL"],
//   },
//   {
//     model: "Carry",
//     versions: [, "Standard"],
//   },
//   {
//     model: "Cervo",
//     versions: [, "G", "TX", "SR"],
//   },
//   {
//     model: "Ciaz",
//     versions: [, "Manual", "Automatic"],
//   },
//   {
//     model: "Escudo",
//     versions: [
//       ,
//       "2.4 HELLY HANSEN LIMITED",
//       "2.4 ONEILL LIMITED",
//       "2.4 SALOMON LIMITED",
//       "2.4 XE",
//       "2.4 XG",
//       "2.4X-ADVENTURE",
//       "3.2XS",
//     ],
//   },
//   {
//     model: "Every",
//     versions: [
//       ,
//       "Join",
//       "GA",
//       "Join Turbo",
//       "PC",
//       "PU",
//       "PA",
//       "GA",
//       "PA",
//       "PU",
//       "PC",
//       "Join",
//       "Join Turbo",
//     ],
//   },
//   {
//     model: "Every Wagon",
//     versions: [
//       ,
//       "JP",
//       "JP Turbo Limited",
//       "JP Turbo",
//       "PZ Turbo",
//       "PZ Turbo Special",
//     ],
//   },
//   {
//     model: "FX",
//     versions: [, "GA"],
//   },
//   {
//     model: "Hustler",
//     versions: [, "G Turbo", "X Turbo"],
//   },
//   {
//     model: "Jimny",
//     versions: [, "JLDX"],
//   },
//   {
//     model: "Jimny Sierra",
//     versions: [, "BASEGRADE", "LAND VENTURE", "WILD WIND", "X-ADVENTURE"],
//   },
//   {
//     model: "Kei",
//     versions: [, "A", "B Turbo"],
//   },
//   {
//     model: "Kizashi",
//     versions: [, "Base Grade"],
//   },
//   {
//     model: "Landy",
//     versions: [, "G", "G S-HYBRID", "S"],
//   },
//   {
//     model: "Liana",
//     versions: [
//       ,
//       "LXi Sport",
//       "RXi",
//       "RXi (CNG)",
//       "RXi (CNG)",
//       "RXi",
//       "LXi",
//       "LXi (CNG)",
//       "AXi",
//       "Eminent",
//       "Eminent Automatic",
//     ],
//   },
//   {
//     model: "Margalla",
//     versions: [, "GL", "GL Plus", "GLX"],
//   },
//   {
//     model: "MR Wagon",
//     versions: [
//       ,
//       "G",
//       "X",
//       "X IDLING STOP",
//       "ECO-X",
//       "ECO-L",
//       "10TH ANNIVERSARY LIMITED",
//       "X SELECTION",
//       "ECO-X SELECTION",
//       "X",
//       "G",
//       "WIT XS",
//       "WIT TS",
//       "WIT GS",
//       "WIT LIMITED",
//       "X",
//       "G",
//     ],
//   },
//   {
//     model: "Palette",
//     versions: [
//       ,
//       "G",
//       "G Limited",
//       "IS Selection",
//       "L",
//       "Limited",
//       "Limited ll",
//       "T",
//       "TS",
//       "X",
//       "XS",
//     ],
//   },
//   {
//     model: "Palette Sw",
//     versions: [, "GS", "Limited", "Limited ll", "TS", "XS", "XS IDLING STOP"],
//   },
//   {
//     model: "Potohar",
//     versions: [, "Basegrade"],
//   },
//   {
//     model: "Ravi",
//     versions: [, "Euro ll"],
//   },
//   {
//     model: "Solio",
//     versions: [
//       ,
//       "E",
//       "E C SELECTION",
//       "G",
//       "G IDLING STOP",
//       "G4",
//       "S",
//       "S IDLING STOP",
//       "S LIMITED II",
//       "Well",
//       "WELL S",
//       "X",
//       "X IDLING STOP",
//     ],
//   },
//   {
//     model: "Solio Bandit",
//     versions: [, "Base Grade", "IDLING STOP"],
//   },
//   {
//     model: "Spacia",
//     versions: [, "T", "X"],
//   },
//   {
//     model: "Splash",
//     versions: [ "Base Grade", "Limited"],
//   },
//   {
//     model: "Swift",
//     versions: ["Please Selec],
//   },
//   {
//     model: "Sx4",
//     versions: [,// Add versions here if any],
//   },
//   {
//     model: "Twin",
//     versions: [,// Add versions here if any],
//   },
//   {
//     model: "Vitara",
//     versions: [,// Add versions here if any],
//   },
//   {
//     model: "Wagon R",
//     versions: [,// Add versions here if any],
//   },
//   {
//     model: "Wagon R Stingray",
//     versions: [,// Add versions here if any],
//   },
// ];

const car = [
  {
    make: "Suzuki",
    models: [
      {
        model: "Mehran",
        versions: [
          "VX Euro II",
          "VXR Euro II",
          "VX Euro II (CNG)",
          "VXR Euro II (CNG)",
          "VX",
          "VXR",
          "VX (CNG)",
          "VXR (CNG)",
        ],
      },
      {
        model: "Cultus",
        versions: [
          "VXL",
          "VXR",
          "VXRi",
          "EURO II",
          "VXLi",
          "VXLi (CNG)",
          "VXRi (CNG)",
          "Euro II (CNG)",
          "Limited Edition",
          "VX",
          "VXR",
          "VXL",
          "VXR (CNG)",
          "VX (CNG)",
          "VXL (CNG)",
        ],
      },
      {
        model: "Alto",
        versions: [
          "X",
          "VP",
          "L",
          "F",
          "VP",
          "G",
          "F",
          "E",
          "G4",
          "X",
          "GII",
          "Memorial of the 30th Birth Anniversary",
          "EII",
          "VS",
          "X",
          "VP",
          "E",
          "G",
          "VXR",
          "VX",
          "VX (CNG)",
          "VXR (CNG)",
        ],
      },
      {
        model: "Bolan",
        versions: ["VX Euro II", "Cargo Van Euro ll", "VX", "VX (CNG)", "GL"],
      },
      {
        model: "Khyber",
        versions: ["GA", "Plus"],
      },
      {
        model: "Alto Eco",
        versions: ["ECO-S", "ECO-L"],
      },
      {
        model: "Alto Lapin",
        versions: [
          "G",
          "XL",
          "TL",
          "X Selection",
          "10th Anniversary Limited",
          "G",
          "G Edition",
          "L",
          "SS",
          "X2",
          "X",
          "Mode",
          "Turbo",
        ],
      },
      {
        model: "APV",
        versions: ["GLX", "GLX (CNG)"],
      },
      {
        model: "Baleno",
        versions: [
          "GLi",
          "GXi",
          "JXR",
          "JXL",
          "Sport",
          "GLi P",
          "GTi 1.6",
          "GL",
        ],
      },
      {
        model: "Carry",
        versions: ["Standard"],
      },
      {
        model: "Cervo",
        versions: ["G", "TX", "SR"],
      },
      {
        model: "Ciaz",
        versions: ["Manual", "Automatic"],
      },
      {
        model: "Escudo",
        versions: [
          "2.4 HELLY HANSEN LIMITED",
          "2.4 ONEILL LIMITED",
          "2.4 SALOMON LIMITED",
          "2.4 XE",
          "2.4 XG",
          "2.4X-ADVENTURE",
          "3.2XS",
        ],
      },
      {
        model: "Every",
        versions: [
          ,
          "Join",
          "GA",
          "Join Turbo",
          "PC",
          "PU",
          "PA",
          "GA",
          "PA",
          "PU",
          "PC",
          "Join",
          "Join Turbo",
        ],
      },
      {
        model: "Every Wagon",
        versions: [
          ,
          "JP",
          "JP Turbo Limited",
          "JP Turbo",
          "PZ Turbo",
          "PZ Turbo Special",
        ],
      },
      {
        model: "FX",
        versions: [, "GA"],
      },
      {
        model: "Hustler",
        versions: [, "G Turbo", "X Turbo"],
      },
      {
        model: "Jimny",
        versions: [, "JLDX"],
      },
      {
        model: "Jimny Sierra",
        versions: [, "BASEGRADE", "LAND VENTURE", "WILD WIND", "X-ADVENTURE"],
      },
      {
        model: "Kei",
        versions: [, "A", "B Turbo"],
      },
      {
        model: "Kizashi",
        versions: [, "Base Grade"],
      },
      {
        model: "Landy",
        versions: [, "G", "G S-HYBRID", "S"],
      },
      {
        model: "Liana",
        versions: [
          ,
          "LXi Sport",
          "RXi",
          "RXi (CNG)",
          "RXi (CNG)",
          "RXi",
          "LXi",
          "LXi (CNG)",
          "AXi",
          "Eminent",
          "Eminent Automatic",
        ],
      },
      {
        model: "Margalla",
        versions: [, "GL", "GL Plus", "GLX"],
      },
      {
        model: "MR Wagon",
        versions: [
          ,
          "G",
          "X",
          "X IDLING STOP",
          "ECO-X",
          "ECO-L",
          "10TH ANNIVERSARY LIMITED",
          "X SELECTION",
          "ECO-X SELECTION",
          "X",
          "G",
          "WIT XS",
          "WIT TS",
          "WIT GS",
          "WIT LIMITED",
          "X",
          "G",
        ],
      },
      {
        model: "Palette",
        versions: [
          ,
          "G",
          "G Limited",
          "IS Selection",
          "L",
          "Limited",
          "Limited ll",
          "T",
          "TS",
          "X",
          "XS",
        ],
      },
      {
        model: "Palette Sw",
        versions: [
          ,
          "GS",
          "Limited",
          "Limited ll",
          "TS",
          "XS",
          "XS IDLING STOP",
        ],
      },
      {
        model: "Potohar",
        versions: [, "Basegrade"],
      },
      {
        model: "Ravi",
        versions: [, "Euro ll"],
      },
      {
        model: "Solio",
        versions: [
          "E",
          "E C SELECTION",
          "G",
          "G IDLING STOP",
          "G4",
          "S",
          "S IDLING STOP",
          "S LIMITED II",
          "Well",
          "WELL S",
          "X",
          "X IDLING STOP",
        ],
      },
      {
        model: "Solio Bandit",
        versions: ["Base Grade", "IDLING STOP"],
      },
      {
        model: "Spacia",
        versions: ["T", "X"],
      },
      {
        model: "Splash",
        versions: ["Base Grade", "Limited"],
      },
      {
        model: "Swift",
        versions: [
          "XG 1.2",
          "XL 1.2",
          "XS 1.2",
          "DLX 1.3",
          "DX 1.3",
          "DLX Automatic 1.3",
          "XG 1.2",
          "XG 1.3",
          "Sport 1.6",
        ],
      },
      {
        model: "Sx4",
        versions: ["1.5G"],
      },
      {
        model: "Twin",
        versions: ["Twin"],
      },
      {
        model: "Vitara",
        versions: ["GL+ 1.6", "GLX 1.6"],
      },
      {
        model: "Wagon R",
        versions: [
          "VX",
          "VXR",
          "VXL",
          "FX Limited",
          "FX",
          "FA",
          "FX Limited",
          "FT Limited",
          "Limited",
          "FX Limited II",
          "FX-S Limited",
          "Stingray Limited",
          "FX Idling Stop",
          "FX",
        ],
      },
      {
        model: "Wagon R Stingray",
        versions: ["X", "T"],
      },
    ],
  },
  {
    make: "Honda",
    models: [
      {
        model: "Civic",
        versions: [
          "Oriel 1.8 i-VTEC CVT",
          "Turbo 1.5 VTEC CVT",
          "1.8 i-VTEC CVT",
          "VTi 1.8 i-VTEC",
          "VTi Oriel 1.8 i-VTEC",
          "VTi Prosmatec 1.8 i-VTEC",
          "VTi Oriel Prosmatec 1.8 i-VTEC",
          "VTi Oriel 1.8 i-VTEC",
          "VTi Oriel Prosmatec 1.8 i-VTEC",
          "VTi 1.8 i-VTEC",
          "VTi Prosmatec 1.8 i-VTEC",
          "EXi",
          "VTi Oriel Prosmatec 1.6",
          "VTi Oriel UG 1.6",
          "VTi Oriel UG Prosmatec 1.6",
          "VTi 1.6",
          "EXi Prosmatec",
          "VTi Prosmatec 1.6",
          "VTi Oriel 1.6",
          "VTi 1.6",
          "VTi Oriel 1.6",
          "EXi Prosmatec",
          "VTi Prosmatec 1.6",
          "EXi",
          "VTi Oriel Prosmatec 1.6",
          "EXi",
          "VTi 1.6",
          "EXi Automatic",
          "VTi Automatic 1.6",
          "VTi Oriel Automatic 1.6",
          "VTi Oriel 1.6",
          "EXi",
          "VTi 1.6",
          "EXi Automatic",
          "VTi Automatic 1.6",
          "EX",
          "EL",
        ],
      },
      {
        model: "City",
        versions: [
          "i-VTEC",
          "i-VTEC Prosmatec",
          "Aspire 1.3 i-VTEC",
          "Aspire Prosmatec 1.3 i-VTEC",
          "Aspire 1.5 i-VTEC",
          "Aspire Prosmatec 1.5 i-VTEC",
          "VTEC Steermatic",
          "i-DSI",
          "i-DSI Vario",
          "i-DSI",
          "i-DSI Vario",
          "EXi",
          "EXi S",
          "EXi S Automatic",
          "EXi",
          "EXi Neo 1.5",
        ],
      },
      {
        model: "Vezel",
        versions: [
          "X",
          "G",
          "S",
          "Hybrid X",
          "Hybrid Z",
          "Hybrid X L Package",
          "Hybrid Z Honda Sensing",
          "Hybrid RS Honda Sensing",
          "Hybrid Z Style Edition",
          "Hybrid X Style Edition",
        ],
      },
      {
        model: "Accord",
        versions: [
          "VTi 2.4",
          "20TL",
          "24TL",
          "Type S",
          "24TL Sports Style",
          "Type S Advance Package",
          "20TL Smart Style Package",
          "Euro R",
          "CL7",
          "CL8",
          "CL9",
          "Type S",
          "CF3",
          "EX",
        ],
      },
      {
        model: "Fit Hybrid",
        versions: [
          "S Package",
          "L Package",
          "F Package",
          "Base Grade 1.5",
          "Navi Premium Selection",
          "Smart Selection",
          "10th Anniversary",
          "XH Selection",
          "RS",
          "Base Grade 1.3",
        ],
      },
      {
        model: "Accord Tourer",
        versions: [
          "2.0TL",
          "2.0TL INTER NAVI PACKAGE",
          "2.0TL SMART STYLE PACKAGE",
          "2.4 TYPE S",
          "2.4 TYPE S ADVANCE PACKAGE",
          "2.4E",
          "2.4IL",
          "24TL",
          "24TL Sports Style",
        ],
      },
      {
        model: "Acty",
        versions: ["Basegrade"],
      },
      {
        model: "Airwave",
        versions: ["M", "ST", "M S Package"],
      },
      {
        model: "BR-V",
        versions: ["i-VTEC S", "i-VTEC"],
      },
      {
        model: "Civic Hybrid",
        versions: ["MXST", "MXB", "MX", "Base Grade"],
      },
      {
        model: "CR-V",
        versions: [
          "G 2.0",
          "G Leather Package 2.0",
          "G 2.4",
          "G Leather Package 2.4",
          "Base Grade 2.4",
          "ZX HDD Navi Smart Edition 2.4",
          "ZL Exclusive 2.4",
          "ZX Alcantara Style 2.4",
          "ZL Alcantara Style 2.4",
          "ZX Exclusive 2.4",
          "ZXI 2.4",
        ],
      },
    ],
  },
  {
    make: "Toyota",
  },
  {
    make: "Nissan",
  },
  {
    make: "Mitsubishi",
  },
  {
    make: "Mazda",
  },
  {
    make: "KIA",
  },
  {
    make: "FAW",
  },
  {
    make: "Fiat",
  },
  {
    make: "Lexus",
  },
  {
    make: "Hyundai",
  },
  {
    make: "BMW",
  },
  {
    make: "Hino",
  },
  {
    make: "Mercedes Benz",
  },
  {
    make: "Audi",
  },
  {
    make: "Austin",
  },
  {
    make: "Bentley",
  },
  {
    make: "Cadillac",
  },
  {
    make: "Chevrolet",
  },
  {
    make: "Chrysler",
  },
  {
    make: "Citroen",
  },
  {
    make: "Daihatsu",
  },
  {
    make: "Datsun",
  },
  {
    make: "Ferrari",
  },
  {
    make: "GMC",
  },
  {
    make: "Haval",
  },
  {
    make: "Isuzu",
  },
  {
    make: "Jaguar",
  },
  {
    make: "Jeep",
  },
  {
    make: "Land Rover",
  },
  {
    make: "Lincoln",
  },
  {
    make: "Maserati",
  },
  {
    make: "Peugeot",
  },
  {
    make: "Porsche",
  },
  {
    make: "Proton",
  },
  {
    make: "Range Rover",
  },
  {
    make: "Rolls Royce",
  },
  {
    make: "Saab",
  },
  {
    make: "Subaru",
  },
  {
    make: "Tesla",
  },
  {
    make: "Volkswagen",
  },
  {
    make: "Volvo",
  },
];

const Numbers = [
  { country: "Afghanistan", code: "+93" },
  { country: "Albania", code: "+355" },
  { country: "Algeria", code: "+213" },
  { country: "American Samoa", code: "+1-684" },
  { country: "Andorra", code: "+376" },
  { country: "Angola", code: "+244" },
  { country: "Anguilla", code: "+1-264" },
  { country: "Antarctica", code: "+672" },
  { country: "Antigua and Barbuda", code: "+1-268" },
  { country: "Argentina", code: "+54" },
  { country: "Armenia", code: "+374" },
  { country: "Aruba", code: "+297" },
  { country: "Australia", code: "+61" },
  { country: "Austria", code: "+43" },
  { country: "Azerbaijan", code: "+994" },
  { country: "Bahamas", code: "+1-242" },
  { country: "Bahrain", code: "+973" },
  { country: "Bangladesh", code: "+880" },
  { country: "Barbados", code: "+1-246" },
  { country: "Belarus", code: "+375" },
  { country: "Belgium", code: "+32" },
  { country: "Belize", code: "+501" },
  { country: "Benin", code: "+229" },
  { country: "Bermuda", code: "+1-441" },
  { country: "Bhutan", code: "+975" },
  { country: "Bolivia", code: "+591" },
  { country: "Bosnia and Herzegovina", code: "+387" },
  { country: "Botswana", code: "+267" },
  { country: "Brazil", code: "+55" },
  { country: "British Indian Ocean Territory", code: "+246" },
  { country: "British Virgin Islands", code: "+1-284" },
  { country: "Brunei", code: "+673" },
  { country: "Bulgaria", code: "+359" },
  { country: "Burkina Faso", code: "+226" },
  { country: "Burundi", code: "+257" },
  { country: "Cambodia", code: "+855" },
  { country: "Cameroon", code: "+237" },
  { country: "Canada", code: "+1" },
  { country: "Cape Verde", code: "+238" },
  { country: "Cayman Islands", code: "+1-345" },
  { country: "Central African Republic", code: "+236" },
  { country: "Chad", code: "+235" },
  { country: "Chile", code: "+56" },
  { country: "China", code: "+86" },
  { country: "Christmas Island", code: "+61" },
  { country: "Cocos Islands", code: "+61" },
  { country: "Colombia", code: "+57" },
  { country: "Comoros", code: "+269" },
  { country: "Cook Islands", code: "+682" },
  { country: "Costa Rica", code: "+506" },
  { country: "Croatia", code: "+385" },
  { country: "Cuba", code: "+53" },
  { country: "Curacao", code: "+599" },
  { country: "Cyprus", code: "+357" },
  { country: "Czech Republic", code: "+420" },
  { country: "Democratic Republic of the Congo", code: "+243" },
  { country: "Denmark", code: "+45" },
  { country: "Djibouti", code: "+253" },
  { country: "Dominica", code: "+1-767" },
  { country: "Dominican Republic", code: "+1-809" },
  { country: "East Timor", code: "+670" },
  { country: "Ecuador", code: "+593" },
  { country: "Egypt", code: "+20" },
  { country: "El Salvador", code: "+503" },
  { country: "Equatorial Guinea", code: "+240" },
  { country: "Eritrea", code: "+291" },
  { country: "Estonia", code: "+372" },
  { country: "Ethiopia", code: "+251" },
  { country: "Falkland Islands", code: "+500" },
  { country: "Faroe Islands", code: "+298" },
  { country: "Fiji", code: "+679" },
  { country: "Finland", code: "+358" },
  { country: "France", code: "+33" },
  { country: "French Polynesia", code: "+689" },
  { country: "Gabon", code: "+241" },
  { country: "Gambia", code: "+220" },
  { country: "Georgia", code: "+995" },
  { country: "Germany", code: "+49" },
  { country: "Ghana", code: "+233" },
  { country: "Gibraltar", code: "+350" },
  { country: "Greece", code: "+30" },
  { country: "Greenland", code: "+299" },
  { country: "Grenada", code: "+1-473" },
  { country: "Guam", code: "+1-671" },
  { country: "Guatemala", code: "+502" },
  { country: "Guernsey", code: "+44-1481" },
  { country: "Guinea", code: "+224" },
  { country: "Guinea-Bissau", code: "+245" },
  { country: "Guyana", code: "+592" },
  { country: "Haiti", code: "+509" },
  { country: "Honduras", code: "+504" },
  { country: "Hong Kong", code: "+852" },
  { country: "Hungary", code: "+36" },
  { country: "Iceland", code: "+354" },
  { country: "India", code: "+91" },
  { country: "Indonesia", code: "+62" },
  { country: "Iran", code: "+98" },
  { country: "Iraq", code: "+964" },
  { country: "Ireland", code: "+353" },
  { country: "Isle of Man", code: "+44-1624" },
  { country: "Israel", code: "+972" },
  { country: "Italy", code: "+39" },
  { country: "Ivory Coast", code: "+225" },
  { country: "Jamaica", code: "+1-876" },
  { country: "Japan", code: "+81" },
  { country: "Jersey", code: "+44-1534" },
  { country: "Jordan", code: "+962" },
  { country: "Kazakhstan", code: "+7" },
  { country: "Kenya", code: "+254" },
  { country: "Kiribati", code: "+686" },
  { country: "Kosovo", code: "+383" },
  { country: "Kuwait", code: "+965" },
  { country: "Kyrgyzstan", code: "+996" },
  { country: "Laos", code: "+856" },
  { country: "Latvia", code: "+371" },
  { country: "Lebanon", code: "+961" },
  { country: "Lesotho", code: "+266" },
  { country: "Liberia", code: "+231" },
  { country: "Libya", code: "+218" },
  { country: "Liechtenstein", code: "+423" },
  { country: "Lithuania", code: "+370" },
  { country: "Luxembourg", code: "+352" },
  { country: "Macau", code: "+853" },
  { country: "Macedonia", code: "+389" },
  { country: "Madagascar", code: "+261" },
  { country: "Malawi", code: "+265" },
  { country: "Malaysia", code: "+60" },
  { country: "Maldives", code: "+960" },
  { country: "Mali", code: "+223" },
  { country: "Malta", code: "+356" },
  { country: "Marshall Islands", code: "+692" },
  { country: "Mauritania", code: "+222" },
  { country: "Mauritius", code: "+230" },
  { country: "Mayotte", code: "+262" },
  { country: "Mexico", code: "+52" },
  { country: "Micronesia", code: "+691" },
  { country: "Moldova", code: "+373" },
  { country: "Monaco", code: "+377" },
  { country: "Mongolia", code: "+976" },
  { country: "Montenegro", code: "+382" },
  { country: "Montserrat", code: "+1-664" },
  { country: "Morocco", code: "+212" },
  { country: "Mozambique", code: "+258" },
  { country: "Myanmar", code: "+95" },
  { country: "Namibia", code: "+264" },
  { country: "Nauru", code: "+674" },
  { country: "Nepal", code: "+977" },
  { country: "Netherlands", code: "+31" },
  { country: "Netherlands Antilles", code: "+599" },
  { country: "New Caledonia", code: "+687" },
  { country: "New Zealand", code: "+64" },
  { country: "Nicaragua", code: "+505" },
  { country: "Niger", code: "+227" },
  { country: "Nigeria", code: "+234" },
  { country: "Niue", code: "+683" },
  { country: "North Korea", code: "+850" },
  { country: "Northern Mariana Islands", code: "+1-670" },
  { country: "Norway", code: "+47" },
  { country: "Oman", code: "+968" },
  { country: "Pakistan", code: "+92" },
  { country: "Palau", code: "+680" },
  { country: "Palestine", code: "+970" },
  { country: "Panama", code: "+507" },
  { country: "Papua New Guinea", code: "+675" },
  { country: "Paraguay", code: "+595" },
  { country: "Peru", code: "+51" },
  { country: "Philippines", code: "+63" },
  { country: "Pitcairn", code: "+64" },
  { country: "Poland", code: "+48" },
  { country: "Portugal", code: "+351" },
  { country: "Puerto Rico", code: "+1-787" },
  { country: "Qatar", code: "+974" },
  { country: "Republic of the Congo", code: "+242" },
  { country: "Reunion", code: "+262" },
  { country: "Romania", code: "+40" },
  { country: "Russia", code: "+7" },
  { country: "Rwanda", code: "+250" },
  { country: "Saint Barthelemy", code: "+590" },
  { country: "Saint Helena", code: "+290" },
  { country: "Saint Kitts and Nevis", code: "+1-869" },
  { country: "Saint Lucia", code: "+1-758" },
  { country: "Saint Martin", code: "+590" },
  { country: "Saint Pierre and Miquelon", code: "+508" },
  { country: "Saint Vincent and the Grenadines", code: "+1-784" },
  { country: "Samoa", code: "+685" },
  { country: "San Marino", code: "+378" },
  { country: "Sao Tome and Principe", code: "+239" },
  { country: "Saudi Arabia", code: "+966" },
  { country: "Senegal", code: "+221" },
  { country: "Serbia", code: "+381" },
  { country: "Seychelles", code: "+248" },
  { country: "Sierra Leone", code: "+232" },
  { country: "Singapore", code: "+65" },
  { country: "Sint Maarten", code: "+1-721" },
  { country: "Slovakia", code: "+421" },
  { country: "Slovenia", code: "+386" },
  { country: "Solomon Islands", code: "+677" },
  { country: "Somalia", code: "+252" },
  { country: "South Africa", code: "+27" },
  { country: "South Korea", code: "+82" },
  { country: "South Sudan", code: "+211" },
  { country: "Spain", code: "+34" },
  { country: "Sri Lanka", code: "+94" },
  { country: "Sudan", code: "+249" },
  { country: "Suriname", code: "+597" },
  { country: "Svalbard and Jan Mayen", code: "+47" },
  { country: "Swaziland", code: "+268" },
  { country: "Sweden", code: "+46" },
  { country: "Switzerland", code: "+41" },
  { country: "Syria", code: "+963" },
  { country: "Taiwan", code: "+886" },
  { country: "Tajikistan", code: "+992" },
  { country: "Tanzania", code: "+255" },
  { country: "Thailand", code: "+66" },
  { country: "Togo", code: "+228" },
  { country: "Tokelau", code: "+690" },
  { country: "Tonga", code: "+676" },
  { country: "Trinidad and Tobago", code: "+1-868" },
  { country: "Tunisia", code: "+216" },
  { country: "Turkey", code: "+90" },
  { country: "Turkmenistan", code: "+993" },
  { country: "Turks and Caicos Islands", code: "+1-649" },
  { country: "Tuvalu", code: "+688" },
  { country: "U.S. Virgin Islands", code: "+1-340" },
  { country: "Uganda", code: "+256" },
  { country: "Ukraine", code: "+380" },
  { country: "United Arab Emirates", code: "+971" },
  { country: "United Kingdom", code: "+44" },
  { country: "United States", code: "+1" },
  { country: "Uruguay", code: "+598" },
  { country: "Uzbekistan", code: "+998" },
  { country: "Vanuatu", code: "+678" },
  { country: "Vatican", code: "+379" },
  { country: "Venezuela", code: "+58" },
  { country: "Vietnam", code: "+84" },
  { country: "Wallis and Futuna", code: "+681" },
  { country: "Western Sahara", code: "+212" },
  { country: "Yemen", code: "+967" },
  { country: "Zambia", code: "+260" },
  { country: "Zimbabwe", code: "+263" },
];
const cities = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Multan",
  "Gujranwala",
  "Hyderabad",
  "Peshawar",
  "Islamabad",
  "Quetta",
  "Sargodha",
  "Sialkot",
  "Bahawalpur",
  "Sukkur",
  "Kandhkot",
  "Shekhupura",
  "Mardan",
  "Gujrat",
  "Larkana",
  "Kasur",
  "Rahim Yar Khan",
  "Sahiwal",
  "Okara",
  "Wah Cantonment",
  "Dera Ghazi Khan",
  "Mingora",
  "Mirpur Khas",
  "Chiniot",
  "Nawabshah",
  "Kamoke",
  "Burewala",
  "Jhelum",
  "Sadiqabad",
  "Khanewal",
  "Hafizabad",
  "Kohat",
  "Jacobabad",
  "Shikarpur",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Bahawalnagar",
  "Abbottabad",
  "Muridke",
  "Pakpattan",
  "Khuzdar",
  "Jaranwala",
  "Chishtian",
  "Daska",
  "Mandi Bahauddin",
  "Ahmadpur East",
  "Kamalia",
  "Tando Adam",
  "Khairpur",
  "Dera Ismail Khan",
  "Vehari",
  "Nowshera",
  "Dadu",
  "Wazirabad",
  "Khushab",
  "Charsada",
  "Swabi",
  "Chakwal",
  "Mianwali",
  "Tando Allahyar",
  "Kot Adu",
  "Farooka",
];

export {
  year,
  price,
  options,
  formItemLayout,
  Area,
  department,
  data,
  experience,
  education,
  country,
  Numbers,
  cities,
  location,
  car,
};
