import "./globals.css";
import { Mitr } from "next/font/google";

const mitr = Mitr({
  weight: '400',
   subsets: ["latin"] });

export const metadata = {
  title: "Dawn Classifieds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mitr.className}>{children}</body>
    </html>
  );
}
